import { existsSync } from 'node:fs';
import puppeteer from 'puppeteer-core';
const [, , url, out, w = '1280', h = '1000'] = process.argv;
const exe = ['C:/Program Files/Google/Chrome/Application/chrome.exe'].find((p) => existsSync(p));
const b = await puppeteer.launch({ executablePath: exe, headless: true });
const p = await b.newPage();
await p.setViewport({ width: Number(w), height: Number(h), deviceScaleFactor: 2 });
const errs = [];
p.on('pageerror', (e) => errs.push(String(e)));
p.on('console', (m) => m.type() === 'error' && errs.push(m.text()));
await p.goto(url, { waitUntil: 'networkidle0', timeout: 60000 });
await p.waitForFunction(() => {
  const el = [...document.querySelectorAll('button')].find((x) => x.textContent?.includes('Elecrtical Procedure'));
  return el && Object.keys(el).some((k) => k.startsWith('__react'));
}, { timeout: 30000 });
await p.evaluate(() => [...document.querySelectorAll('button')].find((x) => x.textContent?.includes('Elecrtical Procedure'))?.click());
await p.waitForFunction(() => document.body.textContent.includes('Electrical Tie-In Procedure'), { timeout: 10000 });
await p.evaluate(() => [...document.querySelectorAll('button')].find((x) => x.textContent?.includes('PRGG-20-E0-PR-001'))?.click());
await new Promise((r) => setTimeout(r, 900));
await p.screenshot({ path: out });
await b.close();
console.log('saved', out);
if (errs.length) console.log('errors:\n ' + errs.join('\n '));
